parameters:
    fioulmarket.price.entity_class.city: 'FioulMarket\PriceBundle\Entity\City'
    fioulmarket.price.entity_class.energy: 'FioulMarket\PriceBundle\Entity\Energy'
    fioulmarket.price.entity_class.price: 'FioulMarket\PriceBundle\Entity\Price'

services:
    fioulmarket.price.entity_manager.city:
        class: Doctrine\Common\Persistence\ObjectManager
        factory: ["@doctrine", getManagerForClass]
        arguments:
            - "%fioulmarket.price.entity_class.city%"

    fioulmarket.price.entity_manager.energy:
        class: Doctrine\Common\Persistence\ObjectManager
        factory: ["@doctrine", getManagerForClass]
        arguments:
            - "%fioulmarket.price.entity_class.energy%"

    fioulmarket.price.entity_manager.price:
        class: Doctrine\Common\Persistence\ObjectManager
        factory: ["@doctrine", getManagerForClass]
        arguments:
            - "%fioulmarket.price.entity_class.price%"

    fioulmarket.price.manager.city:
        class: FioulMarket\PriceBundle\Service\CityManager
        arguments:
            - "@fioulmarket.price.entity_manager.city"
            - "%fioulmarket.price.entity_class.city%"

    fioulmarket.price.manager.energy:
        class: FioulMarket\PriceBundle\Service\EnergyManager
        arguments:
            - "@fioulmarket.price.entity_manager.energy"
            - "%fioulmarket.price.entity_class.energy%"

    fioulmarket.price.manager.price:
        class: FioulMarket\PriceBundle\Service\PriceManager
        arguments:
            - "@fioulmarket.price.entity_manager.price"
            - "%fioulmarket.price.entity_class.price%"

